# Generated by Django 5.1.5 on 2025-02-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertariff',
            name='tariff',
        ),
        migrations.RemoveField(
            model_name='usertariff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertariff',
            name='visa_cart',
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
        migrations.DeleteModel(
            name='UserTariff',
        ),
    ]
