# Generated by Django 5.1.5 on 2025-02-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_remove_usertariff_tariff_remove_usertariff_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания доступа'),
        ),
    ]
