# Generated by Django 5.1.5 on 2025-02-05 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_alter_payment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_course', to='web_site.cours'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='master_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_class_comment', to='web_site.masterclass'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='statya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statya_comment', to='web_site.statya'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_course', to='web_site.cours'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='master_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_class_feedback', to='web_site.masterclass'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='statya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statya_feedback', to='web_site.statya'),
        ),
    ]
